apiVersion: batch/v1
kind: CronJob
metadata:
  name: database-backup
  namespace: yatest
spec:
  schedule: "0 2 * * *"  # Kör varje dag kl 02:00
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: ubuntu:22.04
            command:
            - /bin/bash
            - -c
            - |
              apt-get update && \
              apt-get install -y mysql-client python3-pip && \
              pip3 install awscli && \
              /backup/backup.sh
            env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: backup-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backup-secrets
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              value: stensax
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: backup-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: backup-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: backup-secrets
                  key: S3_BUCKET
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: backup-secrets
                  key: S3_ENDPOINT
            - name: AWS_S3_DISABLE_CHECKSUMS
              value: "1"
            volumeMounts:
            - name: backup-script
              mountPath: /backup
          volumes:
          - name: backup-script
            configMap:
              name: backup-script
              defaultMode: 0755
          restartPolicy: OnFailure 