# Testar CodeBuild webhook
apiVersion: batch/v1
kind: CronJob
metadata:
  name: database-backup
  namespace: yatest
spec:
  schedule: "0 2 * * *"  # Kör varje dag kl 02:00
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: alpine:3.19
            command:
            - /bin/sh
            - -c
            - |
              set -e
              apk add --no-cache mysql-client ca-certificates wget && \
              wget -O /usr/bin/mc https://dl.min.io/client/mc/release/linux-amd64/mc && \
              chmod +x /usr/bin/mc && \
              BACKUP_FILE="/backup-$(date +%Y%m%d-%H%M%S).sql" && \
              mysqldump -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE > $BACKUP_FILE && \
              gzip $BACKUP_FILE && \
              BACKUP_FILE="$BACKUP_FILE.gz" && \
              mc alias set b2 "$S3_ENDPOINT" "$AWS_ACCESS_KEY_ID" "$AWS_SECRET_ACCESS_KEY" && \
              mc cp "$BACKUP_FILE" "b2/$S3_BUCKET/$(basename $BACKUP_FILE)" && \
              rm $BACKUP_FILE
            env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: backup-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backup-secrets
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              value: stensax
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: backup-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: backup-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: backup-secrets
                  key: S3_BUCKET
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: backup-secrets
                  key: S3_ENDPOINT
          restartPolicy: OnFailure 